const data = {
  id: "cs_test_a1HQ05oc4GkCCiy0fZUGLmDbrrztTXUwg71RYn6LZ2csKamRuCcCvLUXCm",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 47992,
  amount_total: 49492,
  automatic_tax: { enabled: false, status: null },
  billing_address_collection: null,
  cancel_url: "http://localhost:3000/cart",
  client_reference_id: null,
  consent: null,
  consent_collection: null,
  created: 1684145632,
  currency: "usd",
  currency_conversion: null,
  custom_fields: [],
  custom_text: { shipping_address: null, submit: null },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: null,
      country: "BD",
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: "shohan.sub.56@gmail.com",
    name: "Shohan",
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1684232031,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {
    images:
      '["https://cdn.shopify.com/s/files/1/0102/4838/8663/products/a-linien-rock_floral-print_vorne_800x.jpg?v=1646934700"]',
    email: "spectra.shohan@gmail.com",
  },
  mode: "payment",
  payment_intent: "pi_3N7yQ5ASSiFLfhkO1nssAwm5",
  payment_link: null,
  payment_method_collection: "always",
  payment_method_options: {},
  payment_method_types: ["card"],
  payment_status: "paid",
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: {
    amount_subtotal: 1500,
    amount_tax: 0,
    amount_total: 1500,
    shipping_rate: "shr_1N7yPbASSiFLfhkOBID5mzgl",
  },
  shipping_details: null,
  shipping_options: [
    {
      shipping_amount: 0,
      shipping_rate: "shr_1N7yPbASSiFLfhkOmc1NawLt",
    },
    {
      shipping_amount: 1500,
      shipping_rate: "shr_1N7yPbASSiFLfhkOBID5mzgl",
    },
  ],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "http://localhost:3000/success",
  total_details: { amount_discount: 0, amount_shipping: 1500, amount_tax: 0 },
  url: null,
};
